
DBFilename = "database.kvdb"
CertsDir = "./certs"

[AdminPanel]
	StaticDir = "./static"
	TemplatesDir = "./templates"
	CookieAuthKey = "12345678901234567890123456789012"
	CookieEncKey = "12345678901234567890123456789012"
	SessionStoreDir = "./temp"
	HTTPAddress = ":8000"
	HTTPSAddress = ":8443"
	SslCert = "./certs/cert.pem"
	SslKey = "./certs/key.pem"

