
DBFilename = "database.kvdb"
CertsDir = "./certs"
CARootsDir = "./certs-ca"

[AdminPanel]
	StaticDir = "./static"
	TemplatesDir = "./templates"
	CookieAuthKey = "12345678901234567890123456789012"
	CookieEncKey = "12345678901234567890123456789012"
	SessionStoreDir = "./temp"
	HTTPAddress = ":8000"
	HTTPSAddress = ":8443"
	SslCert = "./certs/127.0.0.1-server.crt"
	SslKey = "./certs/127.0.0.1-server.pem"

[Ldap]
	# enable users authentication in ldap server
	Enable = true
	# ldap server: host:port
	Server = "localhost:1389"
	# use tls/ssl connection
	StartTLS = false
	# ldap query; %s is replaced by login
	Query="cn=%s,ou=users,dc=test,dc=local"
