
DBFilename = "database.kvdb"
CertsDir = "./certs"

[AdminPanel]
	StaticDir = "./static"
	TemplatesDir = "./templates"
	CookieAuthKey = "12345678901234567890123456789012"
	CookieEncKey = "12345678901234567890123456789012"
	SessionStoreDir = "./temp"
	HTTPAddress = ":8000"
	HTTPSAddress = ":8443"
	SslCert = "./certs/127.0.0.1-server.crt"
	SslKey = "./certs/127.0.0.1-server.pem"

[Ldap]
	Enable = true
	Server = "localhost:1389"
	StartTLS = false
	Query="cn=%s,ou=users,dc=test,dc=local"
